### ISSUE TITLE
Basic Usage not work

### ISSUE THREAD

**Issue by tan-ngoc-fpt** [cpascoe95/typed-validation#7]
typescript v2.6.1
nodejs v8.9.0

Error message
> TS2345:Argument of type 'Validator<Employee>' is not assignable to parameter of type '(arg: any) => ValidationResult<{}>'. Type 'Validator<Employee>' provides no match for the signature '(arg: any): ValidationResult<{}>'.

**Comment by charlespascoe** [comment]
Thanks for creating the issue - I've made some breaking changes to the way `validate` works, but the documentation changes were stashed!

Basically, `validate` now takes an assertion function as the second argument (e.g. `validate(object, conformsTo(validator))` or `validate(arg, isArray(eachItem(isString(minLength(1)))))`), which allows you to validate different types at the root level e.g. arrays.

I'll finish and upload the documentation today.

**Comment by charlespascoe** [comment]
Fixed in 15b82e7a0d9c9df4c6f0ec9c22bbda4b7eff75d8
